# Generated by Django 4.1.4 on 2022-12-11 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestiondesstock", "0008_alter_materiels_image"),
        ("gestionprojets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=50)),
                ("adresse", models.CharField(default=None, max_length=100)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="projet",
            name="budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="projet",
            name="chef_project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chef_project",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="conducteur_travaux",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conducteur_travaux",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="description",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="projet",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="projet",
            name="list_intervenant",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="projet",
            name="list_materiels",
            field=models.ManyToManyField(to="gestiondesstock.materiels"),
        ),
        migrations.AddField(
            model_name="projet",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name="projet",
            name="pieces_jointes",
            field=models.FileField(default=None, upload_to=""),
        ),
        migrations.AddField(
            model_name="projet",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="projet",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "NON DÉBUTÉ"),
                    (2, "EN COURS"),
                    (3, "Terminer"),
                    (4, "ARCHIVER"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default=None, max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "NON DÉBUTÉ"),
                            (2, "EN COURS"),
                            (3, "Terminer"),
                            (4, "ARCHIVER"),
                        ],
                        null=True,
                    ),
                ),
                ("budget", models.IntegerField(default=0)),
                ("pieces_jointes", models.FileField(default=None, upload_to="")),
                (
                    "list_intervenant",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
                (
                    "list_materiels",
                    models.ManyToManyField(to="gestiondesstock.materiels"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projet",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionprojets.client",
            ),
        ),
    ]
