# Generated by Django 4.1.4 on 2022-12-11 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0004_alter_task_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="start_date",
        ),
    ]
