# Generated by Django 4.1.4 on 2022-12-11 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0005_remove_client_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="projet",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestionprojets.projet",
            ),
        ),
    ]
