# Generated by Django 4.1.3 on 2022-12-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojets', '0007_alter_projet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NON DÉBUTÉ'), (2, 'EN COURS'), (3, 'TERMINER'), (4, 'ARCHIVER')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NON DÉBUTÉ'), (2, 'EN COURS'), (3, 'Terminer')], default=1),
        ),
    ]
