# Generated by Django 4.1.3 on 2022-12-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojets', '0008_alter_projet_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='pieces_jointes',
            field=models.FileField(null=True, upload_to='media/upload', verbose_name='image'),
        ),
    ]
