# Generated by Django 4.1.3 on 2022-12-29 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojets', '0011_projet_cordinateur_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='cordinateur_projet',
            new_name='coordinateur',
        ),
    ]
