# Generated by Django 4.1.3 on 2022-12-31 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestionprojets", "0012_rename_cordinateur_projet_projet_coordinateur"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="list_intervenant",
        ),
        migrations.RemoveField(
            model_name="task",
            name="attribuer_a",
        ),
        migrations.AddField(
            model_name="task",
            name="attribuer_a",
            field=models.ManyToManyField(
                related_name="attribuer_a", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
