# Generated by Django 4.1.3 on 2023-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0015_alter_task_pieces_jointes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="pieces_jointes",
            field=models.FileField(
                default=None,
                null=True,
                upload_to="media/upload/documents",
                verbose_name="image",
            ),
        ),
    ]
