# Generated by Django 4.1.3 on 2023-06-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojets', '0016_alter_task_pieces_jointes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pieces_jointes',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/upload/documents', verbose_name='image'),
        ),
    ]
