# Generated by Django 4.1.3 on 2023-12-28 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestionprojets", "0018_phase_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "budget_demande",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "approbation_dg_coordinateur",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "approbation_daf",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "approbation_pdg",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuve", "Approuvé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "chef_projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionprojets.projet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article", models.CharField(max_length=200)),
                ("quantite", models.PositiveIntegerField()),
                (
                    "demande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="gestionprojets.achat",
                    ),
                ),
            ],
        ),
    ]
