# Generated by Django 4.1.3 on 2023-12-28 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0019_achat_articleachat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articleachat",
            old_name="demande",
            new_name="achat",
        ),
        migrations.RemoveField(
            model_name="achat",
            name="budget_demande",
        ),
        migrations.RemoveField(
            model_name="achat",
            name="chef_projet",
        ),
    ]
