# Generated by Django 4.1.3 on 2024-01-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0020_rename_demande_articleachat_achat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleachat",
            name="prix",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
