# Generated by Django 4.1.3 on 2024-01-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0021_articleachat_prix"),
    ]

    operations = [
        migrations.AddField(
            model_name="achat",
            name="status",
            field=models.CharField(
                choices=[
                    ("non_envoyer", "Non Envoyer"),
                    ("envoyer", "Envoyer"),
                    ("archiver", "Archiver"),
                ],
                default="non_envoyer",
                max_length=20,
            ),
        ),
    ]
