# Generated by Django 4.1.3 on 2024-04-24 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestionprojets", "0023_projet_daf_projet_directeur_energie_projet_pdg"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="caissier",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caissier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
