# Generated by Django 4.1.3 on 2024-04-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionprojets", "0024_projet_caissier"),
    ]

    operations = [
        migrations.AddField(
            model_name="achat",
            name="decaisser_budjet",
            field=models.CharField(
                choices=[("oui", "OUI"), ("non", "NON")], default="non", max_length=3
            ),
        ),
    ]
