# Generated by Django 4.1.3 on 2022-11-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dao_number', models.CharField(max_length=200)),
                ('dao_title', models.CharField(max_length=200)),
                ('date_publication', models.DateTimeField()),
                ('date_soumission', models.DateTimeField()),
                ('approbation_chef_service', models.BooleanField()),
                ('approbation_chef_depatement', models.BooleanField()),
                ('approbation_direction', models.BooleanField()),
                ('document_link', models.CharField(max_length=500)),
            ],
        ),
    ]
