# Generated by Django 4.1.3 on 2022-11-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='approbation_chef_depatement',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dao',
            name='approbation_chef_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dao',
            name='approbation_direction',
            field=models.BooleanField(default=False),
        ),
    ]
