# Generated by Django 4.1.3 on 2022-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dao', '0002_alter_dao_approbation_chef_depatement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dao',
            name='document_link',
            field=models.URLField(blank=True),
        ),
    ]
