# Generated by Django 4.1.3 on 2022-12-30 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojets', '0012_rename_cordinateur_projet_projet_coordinateur'),
        ('plannig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='projet',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionprojets.projet'),
        ),
    ]
