# Generated by Django 4.1.3 on 2022-12-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannig', '0002_remove_event_id_event_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='projet',
        ),
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='pk_projet',
            field=models.IntegerField(default=None),
        ),
    ]
