# Generated by Django 4.1.4 on 2022-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestiondesstock", "0003_materiels_image_alter_materiels_entrepot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiels",
            name="image",
            field=models.ImageField(
                default=None,
                null=True,
                upload_to="media",
                verbose_name="image materiel",
            ),
        ),
    ]
