# Generated by Django 4.1.3 on 2022-11-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncouriers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_envoie',
            field=models.DateTimeField(),
        ),
    ]
