# Generated by Django 4.1.3 on 2024-05-20 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperienceSimilaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_marche", models.CharField(max_length=200)),
                ("description_travaux", models.TextField()),
                ("delai_execution_jours", models.PositiveIntegerField()),
                ("delai_execution_mois", models.PositiveIntegerField()),
                ("nom_client", models.CharField(max_length=200)),
                ("financement", models.CharField(max_length=200)),
                ("maitre_ouvrage", models.CharField(max_length=200)),
                (
                    "montant_contrat",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_demarrage_travaux", models.DateTimeField()),
                ("date_fin_travaux", models.DateTimeField()),
                ("objet", models.TextField()),
                ("document", models.FileField(upload_to="documents/")),
                (
                    "dao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences_similaires",
                        to="dao.dao",
                    ),
                ),
            ],
        ),
    ]
