# Generated by Django 4.1.3 on 2024-05-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0002_experiencesimilaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencesimilaire",
            name="objet",
            field=models.CharField(max_length=600),
        ),
    ]
