# Generated by Django 4.1.3 on 2024-05-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0003_alter_experiencesimilaire_objet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencesimilaire",
            name="dao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences_similaires",
                to="dao.dao",
            ),
        ),
    ]
