# Generated by Django 4.1.3 on 2024-05-20 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0004_alter_experiencesimilaire_dao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experiencesimilaire",
            name="delai_execution_mois",
        ),
    ]
