# Generated by Django 4.1.3 on 2025-02-18 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0005_remove_experiencesimilaire_delai_execution_mois"),
    ]

    operations = [
        migrations.CreateModel(
            name="LigneRapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_soumissionnaire", models.CharField(max_length=200)),
                ("observations", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_lot", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="dao",
            old_name="approbation_chef_depatement",
            new_name="is_closed",
        ),
        migrations.RemoveField(
            model_name="dao",
            name="approbation_chef_service",
        ),
        migrations.RemoveField(
            model_name="dao",
            name="approbation_direction",
        ),
        migrations.RemoveField(
            model_name="dao",
            name="document_link",
        ),
        migrations.AlterField(
            model_name="dao",
            name="dao_number",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name="ReponseDAO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_reponse",
                    models.CharField(
                        choices=[
                            ("SCAN", "Document scanné"),
                            ("ZIP", "Dossier/Fichier compressé"),
                            ("URL", "Lien URL"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        blank=True, null=True, upload_to="reponses/dao_%Y/%m/%d/"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "dao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="dao.dao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RapportDepouillement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "dao",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapport_depouillement",
                        to="dao.dao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OffreLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offre_financiere",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "ligne_rapport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres_lots",
                        to="dao.lignerapport",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offres",
                        to="dao.lot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lot",
            name="dao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="dao.dao",
            ),
        ),
        migrations.AddField(
            model_name="lignerapport",
            name="rapport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes",
                to="dao.rapportdepouillement",
            ),
        ),
    ]
