# Generated by Django 4.1.3 on 2025-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0006_lignerapport_lot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dao",
            name="fichier",
            field=models.FileField(
                blank=True, null=True, upload_to="dao_documents/%Y/%m/%d/"
            ),
        ),
    ]
