# Generated by Django 4.1.3 on 2025-02-22 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0007_dao_fichier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Soumissionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("adresse", models.CharField(blank=True, max_length=200, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="lignerapport",
            name="nom_soumissionnaire",
        ),
        migrations.AddField(
            model_name="lignerapport",
            name="soumissionnaire",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes_rapport",
                to="dao.soumissionnaire",
            ),
            preserve_default=False,
        ),
    ]
