# Generated by Django 4.1.3 on 2025-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0008_soumissionnaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offrelot",
            name="devise",
            field=models.CharField(
                choices=[("FCFA", "FCFA"), ("USD", "USD"), ("EUR", "EUR")],
                default="FCFA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="rapportdepouillement",
            name="devise_par_defaut",
            field=models.CharField(
                choices=[("FCFA", "FCFA"), ("USD", "USD"), ("EUR", "EUR")],
                default="FCFA",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="rapportdepouillement",
            name="taux_dollar_fcfa",
            field=models.DecimalField(decimal_places=2, default=630, max_digits=10),
        ),
        migrations.AddField(
            model_name="rapportdepouillement",
            name="taux_euro_fcfa",
            field=models.DecimalField(decimal_places=2, default=656, max_digits=10),
        ),
    ]
