# Generated by Django 4.1.3 on 2025-03-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0009_offrelot_devise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offrelot",
            name="offre_financiere_fcfa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
