# Generated by Django 4.1.3 on 2025-03-04 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0010_offrelot_offre_financiere_fcfa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rapportdepouillement",
            name="devise_par_defaut",
        ),
    ]
