# Generated by Django 4.1.3 on 2025-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0011_remove_rapportdepouillement_devise_par_defaut"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tva_pourcentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=19.0,
                        help_text="Taux de TVA en pourcentage (ex: 19.00 pour 19%)",
                        max_digits=5,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration",
                "verbose_name_plural": "Configurations",
            },
        ),
        migrations.AddField(
            model_name="offrelot",
            name="est_htva",
            field=models.BooleanField(
                default=True,
                help_text="Cochez si le montant est Hors TVA (HTVA)",
                verbose_name="HTVA",
            ),
        ),
        migrations.AddField(
            model_name="offrelot",
            name="offre_financiere_fcfa_ttc",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Montant TTC (FCFA)",
            ),
        ),
    ]
