# Generated by Django 4.1.3 on 2025-03-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0012_configuration_offrelot_est_htva_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ATTRIBUE", "Attribué"),
                            ("REJETE", "Rejeté"),
                            ("EN_ATTENTE", "En attente de décision"),
                        ],
                        default="EN_ATTENTE",
                        max_length=20,
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(
                        blank=True,
                        help_text="Motif de rejet si le soumissionnaire n'est pas retenu",
                        null=True,
                    ),
                ),
                (
                    "document_attribution",
                    models.FileField(
                        blank=True,
                        help_text="Document scanné de la lettre d'attribution",
                        null=True,
                        upload_to="attributions/%Y/%m/%d/",
                    ),
                ),
                ("date_attribution", models.DateField(blank=True, null=True)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="dao.lot",
                    ),
                ),
                (
                    "soumissionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="dao.soumissionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attribution de lot",
                "verbose_name_plural": "Attributions de lots",
                "unique_together": {("lot", "soumissionnaire")},
            },
        ),
    ]
