# Generated by Django 4.1.3 on 2025-03-12 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dao", "0013_attributionlot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experiencesimilaire",
            name="dao",
        ),
    ]
