# Generated by Django 4.1.3 on 2023-11-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(max_length=50, verbose_name="Type d'Action"),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=50, verbose_name="Type d'Entité"),
                ),
                (
                    "entity_id",
                    models.PositiveIntegerField(verbose_name="ID de l'Entité"),
                ),
                (
                    "action_details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Détails de l'Action"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Horodatage"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'Action",
                "verbose_name_plural": "Historiques d'Action",
                "ordering": ["-timestamp"],
            },
        ),
    ]
