# Generated by Django 4.1.3 on 2022-11-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_user_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='photo de profile'),
        ),
    ]
