# Generated by Django 4.1.3 on 2024-04-06 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("1", "Nouveau Projet"),
                            ("2", "Modification de Projet"),
                            ("3", "Nouvelle Tâche"),
                            ("4", "Mise à jour de Tâche"),
                            ("5", "Autre"),
                        ],
                        max_length=1,
                    ),
                ),
                ("message", models.TextField()),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("extra_info", models.JSONField(blank=True, null=True)),
                ("send_email", models.BooleanField(default=False)),
                (
                    "email_subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_template", models.TextField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_notifly.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="notification",
            name="recipients",
            field=models.ManyToManyField(
                related_name="notifications",
                through="django_notifly.UserNotification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
