# Generated by Django 4.1.3 on 2024-04-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_notifly", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("1", "Nouveau Projet"),
                    ("2", "Modification de Projet"),
                    ("3", "Nouvelle Tâche"),
                    ("4", "Mise à jour de Tâche"),
                    ("5", "Demande d'achats"),
                    ("6", "Autre"),
                ],
                max_length=1,
            ),
        ),
    ]
