# Generated by Django 4.1.3 on 2022-11-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objet", models.CharField(default=None, max_length=200)),
                ("messages", models.TextField()),
                ("date_envoie", models.DateTimeField()),
                ("status_envoie", models.BooleanField(default=False)),
            ],
        ),
    ]
