# Generated by Django 4.1.3 on 2022-11-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gestioncouriers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="emetteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emetteur_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recepteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recepteur_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
