# Generated by Django 4.1.3 on 2023-11-17 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestioncouriers", "0006_message_projet_messagepredefini"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagepredefini",
            name="projet",
        ),
    ]
