# Generated by Django 4.1.4 on 2022-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fonction",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assistant DAO"),
                    (2, "Chef Service Etude"),
                    (3, "Chef Departement Etude"),
                    (4, "Directeur Generale"),
                    (5, "admin"),
                    (6, "Coordinateur des Operations"),
                    (7, "Conducteurs des Travaux"),
                    (8, "Chef de Projet"),
                    (9, "DEGP"),
                    (10, "magasinier"),
                ],
                null=True,
            ),
        ),
    ]
