# Generated by Django 4.1.3 on 2023-12-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0004_alter_user_fonction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fonction",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Assistant DAO"),
                    (2, "Chef Service Etude"),
                    (3, "Chef Departement Etude"),
                    (4, "Directeur Energie"),
                    (5, "admin"),
                    (6, "Coordinateur des Operations"),
                    (7, "Conducteurs des Travaux"),
                    (8, "Chef de Projet"),
                    (9, "DEGP"),
                    (10, "Magasinier"),
                    (11, "Intervenant"),
                    (12, "PDG"),
                    (13, "DAF"),
                ],
                null=True,
            ),
        ),
    ]
